set encoding=utf8                          " utf8 everywhere
set t_Co=256                               " Enable 256 colors
syntax on                                  " Syntax highlighting on
syntax enable                              " Yep, really
if &term =~ '256color' | set t_ut= | endif " Disable Background Color Erase (tmux)

let mapleader=' '               " Set <Leader> to spacebar
set nonumber                    " Line numbers are good
set backspace=indent,eol,start  " Allow backspace in insert mode
set history=1000                " Store lots of :cmdline history
set showcmd                     " Show incomplete cmds down the bottom
set showmode                    " Show current mode down the bottom
set gcr=a:blinkon0              " Disable cursor blink
set autoread                    " Reload files changed outside vim
set laststatus=2                " Always show status line
set hidden                      " Buffers can exist in the background
set splitright                  " Opens vertical split right of current window
set splitbelow                  " Opens horizontal split below current window
set shell=/bin/bash             " Run commands in bash
au FocusGained * :checktime     " Automatically reload files when changed

filetype plugin on
filetype indent on
set autoindent       " We've automated our indentation, and now there's fewer jobs
set smartindent      " Indents didn't drop out of high school. High five
set smarttab         " Tabs with a PhD
set shiftwidth=2     " Tabs are now 2 width long
set softtabstop=2
set tabstop=2
set expandtab
set nowrap           " Don't wrap lines
set linebreak        " Wrap lines at convenient points
set formatoptions+=j " Auto collapse comments
set textwidth=80     " Show gutter at 80 chars

set scrolloff=10
set sidescrolloff=15
set sidescroll=1

vnoremap < <gv
vnoremap > >gv
