#!/bin/bash
set -ex
dirname="$(dirname "$(readlink -f "$0")")"
source "$dirname/_shared.sh"

mkdir -p "$HOME/services"
mkdir -p "$HOME/raw"
mkdir -p "$HOME/blog"
mkdir -p "$HOME/bin"

_link "$__dirname/dotfiles" "$HOME/dotfiles"
_link "$__dirname/README.md" "$HOME/README.md"
_link "$__dirname/scripts" "$HOME/scripts"

"$dirname/install_binaries"
"$dirname/install_dotfiles"
