#!/bin/bash
set -ex
dirname="$(dirname "$(readlink -f "$0")")"
source "$dirname/_shared.sh"

sudo apt install -y python-certbot-nginx -t stretch-backports

# alternatively use `certbot run -n --nginx`, but that will modify conf files
sudo certbot certonly -n --standalone \
  -d yoshuawuyts.com \
  -d www.yoshuawuyts.com \
  -m yoshuawuyts@gmail.com \
  --agree-tos

if [ ! -f /etc/cron.d/certbot ]; then
  _link "$dirname/../cron/certbot" "/etc/cron.d/certbot"
fi
