#!/bin/bash
set +ex

# Update kernel and linux-base package
apt-get -t jessie-backports install -y \
  linux-base \
  linux-image-4.9.0-0.bpo.2-amd64 \
  linux-headers-4.9.0-0.bpo.2-amd64

# BCC build dependencies:
apt-get install -y debhelper cmake libllvm3.8 llvm-3.8-dev libclang-3.8-dev \
  libelf-dev bison flex libedit-dev clang-format-3.8 python python-netaddr \
  python-pyroute2 luajit libluajit-5.1-dev arping iperf netperf ethtool \
  devscripts zlib1g-dev libfl-dev

dir="$(mktemp)"
pushd "$dir"

# Build
git clone https://github.com/iovisor/bcc.git
cd bcc
debuild -b -uc -us

# Install
cd ..
sudo dpkg -i *bcc*.deb
