#!/bin/bash
set -ex
dirname="$(dirname "$(readlink -f "$0")")"
source "$dirname/_shared.sh"

curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install telegraf influxdb chronograf kapacitor

sudo systemctl daemon-reload

sudo systemctl start influxdb
sudo systemctl enable influxdb
sudo systemctl enable telegraf
sudo systemctl start telegraf
sudo systemctl enable kapacitor
sudo systemctl start kapacitor
sudo systemctl enable chronograf
sudo systemctl start chronograf
