#!/bin/sh

echo 'deb http://mirrors.digitalocean.com/debian stretch-backports main contrib non-free' \
  >> /etc/apt/sources.list
echo 'deb-src http://mirrors.digitalocean.com/debian stretch-backports main contrib non-free' \
  >> /etc/apt/sources.list

sudo apt-get update
sudo apt install -y python-certbot-nginx -t stretch-backports

# TODO: use --certonly
sudo certbot -n --nginx \
  -d yoshuawuyts.com \
  -d www.yoshuawuyts.com \
  -m yoshuawuyts@gmail.com \
  --agree-tos
